name: 'Bump version and publish release action'
description: 'This action is bump version from latest release, publish release with changes note and push to version branch'
author: 'MeilCli'
branding:
  icon: package
  color: gray-dark
inputs:
  repository:
    description: 'running repository, format: owner/repository'
    required: true
    default: ${{ github.repository }}
  github_token:
    description: 'github token, using to read and write repository'
    required: true
    default: ${{ github.token }}
  commit_user:
    description: 'the commit user'
    required: true
    default: 'github-action'
  commit_email:
    description: 'the commit user`s email'
    required: true
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  config_path:
    description: 'config file path'
    required: true
  bump:
    description: 'how to bump version, value: major or minor or patch or empty string'
  dry_run:
    description: 'if true, not create and push this changes, and output release informations'
  draft:
    description: 'if true, create release as draft'
  pre_release:
    description: 'if true, create release as pre release'
  base_url:
    description: "The where the repo is hosted."
    default: "github.com"
  force_versioning:
    description: 'Manually set the version'
outputs:
  current_version:
    description: 'calculated current version'
  next_version:
    description: 'calculated next version'
  release:
    description: 'the response json of created release'
runs:
  using: 'node16'
  main: 'dist/index.js'
